{% set name = "gavicore" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gavicore-{{ version }}.tar.gz
  sha256: f4e0e614dc6e3eb304958ae282d496b03a6770e7f7306920c6f23c6e1c5a4d4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic
    - pyyaml
    - typer >=0.26.0,<1

test:
  imports:
    - gavicore
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/gavicore
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: Provides common pydantic data classes and utilities for other Eozilla packages.
  description: |
    The Eozilla 🦖 Gavicore package provides common pydantic data classes and utilities.
    Eozilla is a suite of tools for workflow orchestration systems and a
    [OGC API - Processes](https://github.com/opengeospatial/ogcapi-processes)
    implementation.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
